import { Router, type IRouter } from "express";
import healthRouter from "./health";
import questionsRouter from "./questions";
import attemptsRouter from "./attempts";
import discussionsRouter from "./discussions";
import usersRouter from "./users";
import statsRouter from "./stats";
import authLocalRouter from "./authLocal";
import authGoogleRouter from "./auth";
import passwordResetRouter from "./passwordReset";
import passagesRouter from "./passages";
import pdfExtractRouter from "./pdfExtract";
import chaptersRouter from "./chapters";
import appSettingsRouter from "./appSettings";
import seenQuestionsRouter from "./seenQuestions";
import bookmarksRouter from "./bookmarks";
import notesRouter from "./notes";
import questionAttemptsRouter from "./questionAttempts";
import dailyChallengeRouter from "./dailyChallenge";
import performanceRouter from "./performance";
import syllabusProgressRouter from "./syllabusProgress";
import customQuizRouter from "./customQuiz";
import shortNotesRouter from "./shortNotes";
import flashcardsRouter from "./flashcards";
import comparisonsRouter from "./comparisons";
import memoryPalaceRouter from "./memoryPalace";
import quotesRouter from "./quotes";
import spacedRepetitionRouter from "./spacedRepetition";
import samplePapersRouter from "./samplePapers";
import xpRouter from "./xp";

const router: IRouter = Router();

router.use(authLocalRouter);
router.use(authGoogleRouter);
router.use(passwordResetRouter);
router.use(healthRouter);
router.use(questionsRouter);
router.use(attemptsRouter);
router.use(discussionsRouter);
router.use(usersRouter);
router.use(statsRouter);
router.use(passagesRouter);
router.use(pdfExtractRouter);
router.use(chaptersRouter);
router.use(appSettingsRouter);
router.use(seenQuestionsRouter);
router.use(bookmarksRouter);
router.use(notesRouter);
router.use(questionAttemptsRouter);
router.use(dailyChallengeRouter);
router.use(performanceRouter);
router.use(syllabusProgressRouter);
router.use(customQuizRouter);
router.use(shortNotesRouter);
router.use(flashcardsRouter);
router.use(comparisonsRouter);
router.use(memoryPalaceRouter);
router.use(quotesRouter);
router.use(spacedRepetitionRouter);
router.use(samplePapersRouter);
router.use(xpRouter);

export default router;
