import { Router, type IRouter } from "express";
import healthRouter from "./health";
import questionsRouter from "./questions";
import attemptsRouter from "./attempts";
import discussionsRouter from "./discussions";
import usersRouter from "./users";
import statsRouter from "./stats";
import authLocalRouter from "./authLocal";
import passagesRouter from "./passages";
import pdfExtractRouter from "./pdfExtract";
import chaptersRouter from "./chapters";
import appSettingsRouter from "./appSettings";
import seenQuestionsRouter from "./seenQuestions";
import bookmarksRouter from "./bookmarks";
import notesRouter from "./notes";
import questionAttemptsRouter from "./questionAttempts";
import dailyChallengeRouter from "./dailyChallenge";
import performanceRouter from "./performance";
import syllabusProgressRouter from "./syllabusProgress";
import customQuizRouter from "./customQuiz";

const router: IRouter = Router();

router.use(authLocalRouter);
router.use(healthRouter);
router.use(questionsRouter);
router.use(attemptsRouter);
router.use(discussionsRouter);
router.use(usersRouter);
router.use(statsRouter);
router.use(passagesRouter);
router.use(pdfExtractRouter);
router.use(chaptersRouter);
router.use(appSettingsRouter);
router.use(seenQuestionsRouter);
router.use(bookmarksRouter);
router.use(notesRouter);
router.use(questionAttemptsRouter);
router.use(dailyChallengeRouter);
router.use(performanceRouter);
router.use(syllabusProgressRouter);
router.use(customQuizRouter);

export default router;
