// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/biospark-home/ClinicalFocus.tsx": () => import("../components/mockups/biospark-home/ClinicalFocus.tsx"),
  "./components/mockups/biospark-home/ElectricEnergy.tsx": () => import("../components/mockups/biospark-home/ElectricEnergy.tsx"),
  "./components/mockups/biospark-home/WarmScholar.tsx": () => import("../components/mockups/biospark-home/WarmScholar.tsx")
};
