export type Chapter = {
  id: string;
  name: string;
  subject: string;
  class: string;
  subunits: string[];
};

export const chapters11: Chapter[] = [
  {
    id: "the-living-world",
    name: "The Living World",
    subject: "Biology",
    class: "11",
    subunits: [
      "Introduction",
      "What is Living?",
      "Diversity in the Living World",
      "Taxonomic Categories",
      "Taxonomical Aids",
    ],
  },
  {
    id: "biological-classification",
    name: "Biological Classification",
    subject: "Biology",
    class: "11",
    subunits: [
      "Introduction",
      "Kingdom Monera",
      "Kingdom Protista",
      "Kingdom Fungi",
      "Kingdom Plantae",
      "Kingdom Animalia",
      "Viruses, Viroids and Lichens",
    ],
  },
  {
    id: "plant-kingdom",
    name: "Plant Kingdom",
    subject: "Biology",
    class: "11",
    subunits: [
      "Introduction",
      "Algae",
      "Bryophytes",
      "Pteridophytes",
      "Gymnosperms",
      "Angiosperms",
      "Plant Life Cycles and Alternation of Generations",
    ],
  },
  {
    id: "animal-kingdom",
    name: "Animal Kingdom",
    subject: "Biology",
    class: "11",
    subunits: [
      "Introduction",
      "Basis of Classification",
      "Porifera",
      "Coelenterata",
      "Platyhelminthes",
      "Aschelminthes",
      "Annelida",
      "Arthropoda",
      "Mollusca",
      "Echinodermata",
      "Hemichordata",
      "Chordata",
    ],
  },
  {
    id: "morphology-of-flowering-plants",
    name: "Morphology of Flowering Plants",
    subject: "Biology",
    class: "11",
    subunits: [
      "Introduction",
      "The Root",
      "The Stem",
      "The Leaf",
      "The Inflorescence",
      "The Flower",
      "The Fruit",
      "The Seed",
      "Description of Important Families",
    ],
  },
  {
    id: "anatomy-of-flowering-plants",
    name: "Anatomy of Flowering Plants",
    subject: "Biology",
    class: "11",
    subunits: [
      "Introduction",
      "The Tissue",
      "The Tissue System",
      "Anatomy of Dicotyledonous Plants",
      "Anatomy of Monocotyledonous Plants",
      "Secondary Growth",
    ],
  },
  {
    id: "structural-organisation-animals",
    name: "Structural Organisation in Animals",
    subject: "Biology",
    class: "11",
    subunits: [
      "Introduction",
      "Animal Tissues",
      "Organ and Organ System",
      "Earthworm",
      "Cockroach",
      "Frog",
    ],
  },
  {
    id: "cell-unit-of-life",
    name: "Cell – The Unit of Life",
    subject: "Biology",
    class: "11",
    subunits: [
      "Introduction",
      "What is a Cell?",
      "Cell Theory",
      "Overview of Cell",
      "Prokaryotic Cells",
      "Eukaryotic Cells",
    ],
  },
  {
    id: "biomolecules",
    name: "Biomolecules",
    subject: "Biology",
    class: "11",
    subunits: [
      "Introduction",
      "Chemical Composition Analysis",
      "Primary and Secondary Metabolites",
      "Biomacromolecules",
      "Proteins",
      "Polysaccharides",
      "Nucleic Acids",
      "Enzymes",
      "Concept of Metabolism",
    ],
  },
  {
    id: "cell-cycle-and-division",
    name: "Cell Cycle and Cell Division",
    subject: "Biology",
    class: "11",
    subunits: [
      "Introduction",
      "Cell Cycle",
      "Mitosis (M Phase)",
      "Significance of Mitosis",
      "Meiosis",
      "Significance of Meiosis",
    ],
  },
  {
    id: "photosynthesis",
    name: "Photosynthesis in Higher Plants",
    subject: "Biology",
    class: "11",
    subunits: [
      "Introduction",
      "Early Experiments",
      "Where does Photosynthesis Occur?",
      "Pigments Involved",
      "Light Reactions",
      "Electron Transport",
      "Calvin Cycle (C3 Pathway)",
      "C4 Pathway",
      "Photorespiration",
      "Factors Affecting Photosynthesis",
    ],
  },
  {
    id: "respiration-in-plants",
    name: "Respiration in Plants",
    subject: "Biology",
    class: "11",
    subunits: [
      "Introduction",
      "Do Plants Breathe?",
      "Glycolysis",
      "Fermentation",
      "Aerobic Respiration",
      "Krebs Cycle",
      "Respiratory Balance Sheet",
      "Amphibolic Pathway",
      "Respiratory Quotient",
    ],
  },
  {
    id: "plant-growth-and-development",
    name: "Plant Growth and Development",
    subject: "Biology",
    class: "11",
    subunits: [
      "Introduction",
      "Growth",
      "Differentiation, Dedifferentiation and Redifferentiation",
      "Development",
      "Plant Growth Regulators",
      "Auxins, Gibberellins, Cytokinins, ABA, Ethylene",
      "Photoperiodism",
      "Vernalisation",
    ],
  },
  {
    id: "breathing-and-exchange-of-gases",
    name: "Breathing and Exchange of Gases",
    subject: "Biology",
    class: "11",
    subunits: [
      "Introduction",
      "Respiratory Organs",
      "Mechanism of Breathing",
      "Exchange of Gases",
      "Transport of Gases",
      "Regulation of Respiration",
      "Disorders of Respiratory System",
    ],
  },
  {
    id: "body-fluids-and-circulation",
    name: "Body Fluids and Circulation",
    subject: "Biology",
    class: "11",
    subunits: [
      "Introduction",
      "Blood",
      "Lymph",
      "Circulatory Pathways",
      "Human Circulatory System",
      "Cardiac Cycle",
      "Electrocardiograph (ECG)",
      "Double Circulation",
      "Regulation of Cardiac Activity",
      "Disorders of Circulatory System",
    ],
  },
  {
    id: "excretory-products",
    name: "Excretory Products and their Elimination",
    subject: "Biology",
    class: "11",
    subunits: [
      "Introduction",
      "Human Excretory System",
      "Urine Formation",
      "Function of Tubules",
      "Concentration of Filtrate",
      "Regulation of Kidney Function",
      "Micturition",
      "Role of Other Organs in Excretion",
      "Disorders of Excretory System",
    ],
  },
  {
    id: "locomotion-and-movement",
    name: "Locomotion and Movement",
    subject: "Biology",
    class: "11",
    subunits: [
      "Introduction",
      "Types of Movement",
      "Muscle",
      "Skeletal System",
      "Joints",
      "Disorders of Muscular and Skeletal System",
    ],
  },
  {
    id: "neural-control-and-coordination",
    name: "Neural Control and Coordination",
    subject: "Biology",
    class: "11",
    subunits: [
      "Introduction",
      "Neural System",
      "Human Neural System",
      "Neuron – Structure and Function",
      "Central Neural System",
      "Reflex Action and Reflex Arc",
      "Sensory Reception and Processing",
    ],
  },
  {
    id: "chemical-coordination",
    name: "Chemical Coordination and Integration",
    subject: "Biology",
    class: "11",
    subunits: [
      "Introduction",
      "Endocrine Glands and Hormones",
      "Human Endocrine System",
      "Hormones of Heart, Kidney and GI Tract",
      "Mechanism of Hormone Action",
    ],
  },
];

export const chapters12: Chapter[] = [
  {
    id: "sexual-reproduction-flowering-plants",
    name: "Sexual Reproduction in Flowering Plants",
    subject: "Biology",
    class: "12",
    subunits: [
      "Introduction",
      "Flower – Structure and Function",
      "Pre-fertilisation: Structures and Events",
      "Double Fertilisation",
      "Post-fertilisation: Structures and Events",
      "Apomixis and Polyembryony",
    ],
  },
  {
    id: "human-reproduction",
    name: "Human Reproduction",
    subject: "Biology",
    class: "12",
    subunits: [
      "Introduction",
      "Male Reproductive System",
      "Female Reproductive System",
      "Gametogenesis",
      "Menstrual Cycle",
      "Fertilisation and Implantation",
      "Pregnancy and Embryonic Development",
      "Parturition and Lactation",
    ],
  },
  {
    id: "reproductive-health",
    name: "Reproductive Health",
    subject: "Biology",
    class: "12",
    subunits: [
      "Introduction",
      "Reproductive Health – Problems and Strategies",
      "Population Explosion and Birth Control",
      "Medical Termination of Pregnancy",
      "Sexually Transmitted Infections",
      "Infertility",
    ],
  },
  {
    id: "principles-of-inheritance",
    name: "Principles of Inheritance and Variation",
    subject: "Biology",
    class: "12",
    subunits: [
      "Introduction",
      "Mendel's Experiments",
      "Inheritance of One Gene",
      "Inheritance of Two Genes",
      "Sex Determination",
      "Mutation",
      "Genetic Disorders",
    ],
  },
  {
    id: "molecular-basis-of-inheritance",
    name: "Molecular Basis of Inheritance",
    subject: "Biology",
    class: "12",
    subunits: [
      "Introduction",
      "The DNA",
      "Search for Genetic Material",
      "RNA World",
      "Replication",
      "Transcription",
      "Genetic Code",
      "Translation",
      "Regulation of Gene Expression",
      "Human Genome Project",
      "DNA Fingerprinting",
    ],
  },
  {
    id: "evolution",
    name: "Evolution",
    subject: "Biology",
    class: "12",
    subunits: [
      "Introduction",
      "Origin of Life",
      "Evidence for Evolution",
      "Adaptive Radiation",
      "Biological Evolution",
      "Mechanism of Evolution",
      "Hardy-Weinberg Principle",
      "A Brief Account of Evolution",
      "Origin and Evolution of Man",
    ],
  },
  {
    id: "human-health-and-disease",
    name: "Human Health and Disease",
    subject: "Biology",
    class: "12",
    subunits: [
      "Introduction",
      "Common Diseases in Humans",
      "Immunity",
      "AIDS",
      "Cancer",
      "Drugs and Alcohol Abuse",
    ],
  },
  {
    id: "microbes-in-human-welfare",
    name: "Microbes in Human Welfare",
    subject: "Biology",
    class: "12",
    subunits: [
      "Introduction",
      "Microbes in Household Products",
      "Microbes in Industrial Products",
      "Microbes in Sewage Treatment",
      "Microbes in Production of Biogas",
      "Microbes as Biocontrol Agents",
      "Microbes as Biofertilisers",
    ],
  },
  {
    id: "biotechnology-principles",
    name: "Biotechnology – Principles and Processes",
    subject: "Biology",
    class: "12",
    subunits: [
      "Introduction",
      "Principles of Biotechnology",
      "Tools of Recombinant DNA Technology",
      "Processes of Recombinant DNA Technology",
    ],
  },
  {
    id: "biotechnology-applications",
    name: "Biotechnology and its Applications",
    subject: "Biology",
    class: "12",
    subunits: [
      "Introduction",
      "Biotechnological Applications in Agriculture",
      "Biotechnological Applications in Medicine",
      "Transgenic Animals",
      "Ethical Issues",
    ],
  },
  {
    id: "organisms-and-populations",
    name: "Organisms and Populations",
    subject: "Biology",
    class: "12",
    subunits: [
      "Introduction",
      "Organism and its Environment",
      "Major Abiotic Factors",
      "Responses to Abiotic Factors",
      "Adaptations",
      "Population Attributes",
      "Population Growth",
      "Life History Variation",
      "Population Interactions",
    ],
  },
  {
    id: "ecosystem",
    name: "Ecosystem",
    subject: "Biology",
    class: "12",
    subunits: [
      "Introduction",
      "Ecosystem Structure and Function",
      "Productivity",
      "Decomposition",
      "Energy Flow",
      "Ecological Pyramids",
      "Ecological Succession",
      "Nutrient Cycling",
      "Ecosystem Services",
    ],
  },
  {
    id: "biodiversity-and-conservation",
    name: "Biodiversity and Conservation",
    subject: "Biology",
    class: "12",
    subunits: [
      "Introduction",
      "Biodiversity",
      "Biodiversity at Global Level",
      "Importance of Species Diversity",
      "Loss of Biodiversity",
      "Biodiversity Conservation",
    ],
  },
];
